In [9]:
import numpy as np
from numpy.linalg import eig, inv
from numpy import diag

In [2]:
A = np.array([
    [1,2],
    [2,4]
])
A

array([[1, 2],
       [2, 4]])

In [3]:
eigval, eigvec = eig(A)

In [4]:
eigval

array([0., 5.])

In [5]:
#dalam vector satuan
eigvec

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [7]:
eigvec[1]*np.sqrt(5)

array([ 1., -2.])

**rekonstruksi matriks**
* mencari matriks dari informasi vector eigen dan eigen value

In [10]:
eigvec

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [11]:
eigval

array([0., 5.])

In [12]:
diag(eigval)

array([[0., 0.],
       [0., 5.]])

In [14]:
B = eigvec @ diag(eigval) @ inv(eigvec)
B

array([[1., 2.],
       [2., 4.]])

In [15]:
A

array([[1, 2],
       [2, 4]])

B=A