In [1]:
import numpy as np
from numpy.linalg import eig, inv
from numpy import diag

In [2]:
A = np.array([
    [1,2],
    [2,4]
])
A

array([[1, 2],
       [2, 4]])

In [3]:
eigval, eigvec = eig(A)

In [4]:
eigval

array([0., 5.])

In [5]:
#dalam vector satuan
eigvec

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [6]:
eigvec[1]*np.sqrt(5)

array([ 1., -2.])

**rekonstruksi matriks**
* mencari matriks dari informasi vector eigen dan eigen value

In [7]:
eigvec

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [8]:
eigval

array([0., 5.])

In [9]:
diag(eigval)

array([[0., 0.],
       [0., 5.]])

In [10]:
B = eigvec @ diag(eigval) @ inv(eigvec)
B

array([[1., 2.],
       [2., 4.]])

In [11]:
A

array([[1, 2],
       [2, 4]])

B=A

# APLIKASI PADA WEB RANKING

In [27]:
A = np.array([[0, .25, 0, .5, 0, 0],
              [0, 0, 0, 0, 0, 0],
              [.5, .25, 0, 0, 0, .5],
              [.5, .25, 0, 0, 0, .5],
              [0, .25, 0, .5, 0, 0],
              [0, 0, 0, 0, 0, 0]])
A

array([[0.  , 0.25, 0.  , 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.5 , 0.25, 0.  , 0.  , 0.  , 0.5 ],
       [0.5 , 0.25, 0.  , 0.  , 0.  , 0.5 ],
       [0.  , 0.25, 0.  , 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [28]:
eigval, eigvec = eig(A)

In [29]:
eigval

array([ 0. ,  0. ,  0.5, -0.5,  0. ,  0. ])

In [30]:
np.argmax(eigval)

2

In [31]:
eigvec[2]

array([0.        , 1.        , 0.5       , 0.5       , 0.52716004,
       0.29839202])

In [32]:
np.argmax(eigvec[2])

1