# NON-GRADED CHALLENGE 4

In [1]:
import numpy as np

## No. 1

In [2]:
a = np.array([
    [23,50], [7, 12]
])

b = np.array([
    [57, 67], [99, 43]
])

c = np.array([
    [75, 21], [57, 12]
])

d = np.array([
    [87, 26], [18, 84]
])

In [11]:
tensor = np.array([
    [a, b], [c, d]
])

print(tensor)

[[[[23 50]
   [ 7 12]]

  [[57 67]
   [99 43]]]


 [[[75 21]
   [57 12]]

  [[87 26]
   [18 84]]]]


## No. 2

In [14]:
A = np.array([
    [23, 50, 19],
    [7, 12, 109],
    [57, 67, 98]
])

B = np.array([17, 22, 19])

In [15]:
A@B

array([1852, 2454, 4305])

## No. 3

In [16]:
from numpy.linalg import det, inv

In [17]:
print(A)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


In [18]:
print(A.T)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [19]:
det(A)

131344.0000000002

In [20]:
inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])