# NON GRADED CHALLENGE 5

In [1]:
import numpy as np
from numpy.linalg import eig, inv

In [12]:
A = np.array([
    [1, -1],
    [6, 4]
])

print(A)

[[ 1 -1]
 [ 6  4]]


In [13]:
eigval, eigvec = eig(A)

In [14]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])

In [15]:
eigvec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])