# MATRIKS

In [7]:
import numpy as np

In [8]:
mat = np.array([[1,2,3],
                [3,4,5],
                [5,6,7]])
print(mat)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [9]:
mat.shape

(3, 3)

## Akses Elemen Matriks

In [10]:
mat[1]

array([3, 4, 5])

In [11]:
mat[0,1]

2

In [12]:
mat[2,1]

6

In [13]:
mat[:,2]

array([3, 5, 7])

In [15]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
np.diag(np.diag(mat))

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 7]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Operasi Matriks

**Penjumlahan n Pengurangan**

In [25]:
mat2 = np.array([[2,5,3],
                 [7,3,6],
                 [4,9,1]])
mat2

array([[2, 5, 3],
       [7, 3, 6],
       [4, 9, 1]])

In [26]:
print(mat)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [27]:
mat + mat2

array([[ 3,  7,  6],
       [10,  7, 11],
       [ 9, 15,  8]])

**Pembagian**

In [28]:
mat/mat2

array([[0.5       , 0.4       , 1.        ],
       [0.42857143, 1.33333333, 0.83333333],
       [1.25      , 0.66666667, 7.        ]])

**Perkalian**

* Scalar-Matriks
* hadamard product (element wise)
* matrix-matrix (@ dot)

In [29]:
#matrix-scalar
10*mat

array([[10, 20, 30],
       [30, 40, 50],
       [50, 60, 70]])

In [30]:
#hadamard
mat * mat2

array([[ 2, 10,  9],
       [21, 12, 30],
       [20, 54,  7]])

In [31]:
#matrix-matrix (@ dot)
mat @ mat2

array([[ 28,  38,  18],
       [ 54,  72,  38],
       [ 80, 106,  58]])

In [32]:
mat.dot(mat2)

array([[ 28,  38,  18],
       [ 54,  72,  38],
       [ 80, 106,  58]])

**Transpose**

In [33]:
mat.T

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7]])

**Inverse**

In [34]:
mat

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [35]:
mat2

array([[2, 5, 3],
       [7, 3, 6],
       [4, 9, 1]])

In [44]:
D = np.array([[3,4],
             [5,6]])
D_adjecent = np.array([[6,-4],
                       [-5,3]])

In [45]:
inv_D = 1/np.linalg.det(D)*D_adjecent
inv_D

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [43]:
inv_d = np.linalg.inv(D)
inv_d

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

**Determinant**

In [46]:
np.linalg.det(D)

-1.9999999999999971

# TENSOR

In [50]:
X = np.array([
    [2,4,5,3],
    [5,5,3,2]
])
print(X)
print('')
print('shape: ', X.shape)

[[2 4 5 3]
 [5 5 3 2]]

shape:  (2, 4)


In [51]:
Y = np.array([
    [5,4,3,6],
    [1,5,5,8]
])
print(Y)
print('')
print('shape: ', Y.shape)

[[5 4 3 6]
 [1 5 5 8]]

shape:  (2, 4)


In [52]:
Z = np.array([
    [6,3,3,1],
    [1,2,6,8]
])
print(Z)
print('')
print('shape: ', Z.shape)

[[6 3 3 1]
 [1 2 6 8]]

shape:  (2, 4)


In [55]:
list_matrix = [X, Y, Z]
tensor = np.array(list_matrix)
print(tensor)

[[[2 4 5 3]
  [5 5 3 2]]

 [[5 4 3 6]
  [1 5 5 8]]

 [[6 3 3 1]
  [1 2 6 8]]]


In [57]:
tensor[0]

array([[2, 4, 5, 3],
       [5, 5, 3, 2]])

In [58]:
tensor[0,1,:]

array([5, 5, 3, 2])

In [59]:
tensor[0,:,-1]

array([3, 2])