# Vector

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
#Penjumlah 2 list

list_1 = [1, 2, 3]
list_2 = [4, 5, 6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [4]:
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)
arr_1 + arr_2

array([5, 7, 9])

In [5]:
arr_1[2]

3

In [6]:
arr_1.size

3

# Vector norm

`np.linalg.norm(v)`

In [7]:
print(arr_1, arr_2)

[1 2 3] [4 5 6]


In [8]:
#vector norm arr_1 
np.linalg.norm(arr_1)

3.7416573867739413

In [9]:
#(deafult euclidean)
np.linalg.norm([3, 4])

5.0

In [10]:
#manhattan
np.linalg.norm([3, 4], 1)

7.0

# Operasi Aritmatika

## Penjumlahan

In [11]:
print(arr_1, arr_2)

[1 2 3] [4 5 6]


In [12]:
#penjumlahan vector dengan skalar
arr_1 + 10

array([11, 12, 13])

In [13]:
#penjumlahan vector dengan vector
arr_1 + arr_1

array([2, 4, 6])

## Pembagian

In [14]:
#vector dengan scalar
arr_1/2

array([0.5, 1. , 1.5])

In [15]:
#vector dengan vector
arr_1/arr_2

array([0.25, 0.4 , 0.5 ])

## Perkalian

* Dengan skalar
* dengan vektor
* dot product

In [16]:
#dengan skalar
arr_1*10

array([10, 20, 30])

In [17]:
#vector vs vector
arr_1*arr_2

array([ 4, 10, 18])

In [18]:
#dor product
arr_1.dot(arr_2)

32

In [19]:
np.dot(arr_1, arr_2)

32

In [20]:
arr_1 @ arr_2

32

## cosine similarity

In [24]:
cos_theta = (arr_1 @ arr_2) / (np.linalg.norm(arr_1) * np.linalg.norm(arr_2))
cos_theta

0.9746318461970762

In [27]:
radians = np.arccos(cos_theta)
radians

0.2257261285527342

In [28]:
#sudut yang terbentuk antara 2 buah vector
np.degrees(radians)

12.933154491899135

## case study
melihat kemiripan antara 2 kalimat
* kalimat_1 = saya pergi ke rumah nenek saya
* kalimat_2 = saya pergi ke rumah kakek saya

In [29]:
kal_1 = [2,1,1,1,1,0]
kal_2 = [2,1,1,1,0,1]

kal_1 = np.array(kal_1)
kal_2 = np.array(kal_2)

print(kal_1, kal_2)

[2 1 1 1 1 0] [2 1 1 1 0 1]


In [31]:
cos_theta = (kal_1 @ kal_2) / (np.linalg.norm(kal_1) * np.linalg.norm(kal_2))
cos_theta

0.8749999999999998

skor 0.87 mengindikasikan bahwa 2 kalimat tersbut mirip