In [4]:
import numpy as np

In [5]:
a =  np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.empty(4)

array([1., 1., 1., 1.])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.linspace(1,2,9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [15]:
b = np.append(a, [1,2,3])
b

array([1, 2, 3, 4, 5, 1, 2, 3])

In [21]:
np.delete(b, (2))

array([1, 2, 4, 5, 1, 2, 3])

In [32]:
#ascending
np.sort(b)

array([1, 1, 2, 2, 3, 3, 4, 5])

In [28]:
#descending
#-np.sort(-b)
np.sort(b)[::-1]

array([5, 4, 3, 3, 2, 2, 1, 1])

In [58]:
arrr = np.array([2,5,2,5,10,15,1,0])
arrr.argmax()
#arrr.argmin()

5

# 0 D

In [35]:
arr = np.array(4)
arr

array(4)

In [37]:
arr.ndim

0

# 1D

In [38]:
arr =  np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [39]:
arr.ndim

1

# 2D

In [64]:
arr =  np.array([[1,6],[2,7]])
arr

array([[1, 6],
       [2, 7]])

In [48]:
arr.ndim

2

In [49]:
arr.shape

(2, 2)

# 3D

In [42]:
arr =  np.array([[[1,6],[2,7],[3,8]]])
arr

array([[[1, 6],
        [2, 7],
        [3, 8]]])

In [43]:
arr.ndim

3

In [45]:
arr.shape

(1, 3, 2)

In [46]:
arr.size

6

# RESHAPE

In [59]:
arr2 = np.linspace(1,4,6)
arr2

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [56]:
arr2.reshape(3,2)

array([[1. , 1.6],
       [2.2, 2.8],
       [3.4, 4. ]])

In [67]:
arr3 = np.expand_dims(arr2, axis=1)
arr3

array([[1. ],
       [1.6],
       [2.2],
       [2.8],
       [3.4],
       [4. ]])

# SLICING

In [77]:
arr = np.array([2,3,7,8,9])
print(arr[::2])

[2 7 9]


In [91]:
print(arr[2:5])

[3 7 8 9]


In [75]:
print(arr[2:5:3])

[7]


In [87]:
arr2 = np.array([[2,3,7,8,9],[1,3,6,8,7]])
print(arr2[1, 1:3])

[3 6]


In [90]:
print(arr2[0:2, 1])

[3 3]


In [93]:
print(arr2[0:2, 1:3])

[[3 7]
 [3 6]]


In [94]:
#filtering
print(arr2[arr2>=4])

[7 8 9 6 8 7]


In [95]:
a_1 = np.array([[3,2],[4,5]])
a_2 = np.array([[5,3],[7,2]])

In [96]:
np.vstack((a_1,a_2))

array([[3, 2],
       [4, 5],
       [5, 3],
       [7, 2]])

In [97]:
np.hstack((a_1,a_2))

array([[3, 2, 5, 3],
       [4, 5, 7, 2]])

In [99]:
arr4 = np.array([3,4,3,7,4,5,4,6,3,9,12,15])
new_arr = arr4.reshape(2,3, -1)
print(new_arr)

[[[ 3  4]
  [ 3  7]
  [ 4  5]]

 [[ 4  6]
  [ 3  9]
  [12 15]]]
